name: flutterui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# added dependencies
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audios/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/lottiefiles/
    - assets/texts/
    - assets/videos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"